language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'
  - '8.1'
  - '8.2'

before_script:
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

before_deploy:
    - composer install --no-dev

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
